version: '3.8'
services:
  postgress:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: auth1234
      POSTGRES_DB: nest_auth
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
